x-superset-volumes: &superset-volumes
  # /app/pythonpath_docker will be appended to the PYTHONPATH in the final container
  - ./docker:/app/docker
  - ./superset:/app/superset
  - ./superset-frontend:/app/superset-frontend
  - superset_home:/app/superset_home
  - ./tests:/app/tests

version: "3.7"
services:
  superset:
    image: apache/superset:0b49327cfb69b6596221cf3b8f7b8338d5772f27
    container_name: superset_app
    #    command: ["/app/docker/docker-bootstrap.sh", "app"]
    restart: always
    ports:
      - 8088:8088
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
#    user: *superset-user
#    depends_on: *superset-depends-on
#    volumes: *superset-volumes
#    environment:
#      CYPRESS_CONFIG: "${CYPRESS_CONFIG}"
#volumes:
#  superset_home:
#    external: false
#  db_home:
#    external: false